_internal_variables:
  template: !update 'config/node_classification/template.yaml'
  model_name: &model_name 'DeeperGCN'

logs:
  name: !join [*model_name, _base]

loader:
  load_edge_attr: true

module:
  model:
    name: *model_name
    kwargs:
      hidden_feat: 64
      in_features: None
      num_layers: 28
