_internal_variables:
  template: !update 'config/node_classification/template.yaml'
  model_name: &model_name 'DeeperGCN'
  home_path: &home_path !home_path

logs:
  save_dir: !join [*home_path, /results/plant-ct-logs/best/]
  name: *model_name

loader:
  load_edge_attr: false

module:
  optimizer:
    lr: 1e-2
    wd: 0

  model:
    name: *model_name
    kwargs:
      hidden_feat: 128
      in_features: None
      num_layers: 16
      dropout: 0.1

trainer:
  max_epochs: 200