
logs:
  path: "/results/plant-ct-logs/baseline/"
  run_keyword: "base"

trainer:
  gpus: 1
  max_steps: 12000

loader:
  path: "/data/ovules/ovules-celltype-processed/**/*.h5"
  load_edge_attr: true
  batch: 1

pl_lightning:
  config_optimizer:
    lr: 1e-3
    wd: 1e-6

  config_model:
    name: 'DeeperGCN'
    kwargs:
      out_features: 10
      hidden_feat: 64
      in_features: None
      num_layers: 28
