_internal_variables:
  template: !update 'config/node_classification/template.yaml'
  model_name: &model_name 'GAT2'

logs:
  name: !join [*model_name, _base]

module:
  model:
    name: *model_name
    kwargs:
      hidden_feat: 128
