
logs:
  path: "/results/plant-ct-logs/baseline/"
  run_keyword: "edge"

trainer:
  gpus: 1
  max_steps: 12000

loader:
  path: "/data/ovules/ovules-celltype-processed/**/*.h5"
  load_edge_attr: true
  batch: 1

pl_lightning:
  config_optimizer:
    lr: 1e-4
    wd: 1e-6

  config_model:
    name: 'GAT2'
    kwargs:
      out_features: 10
      hidden_feat: 128
      layer1_kwargs:
        gat_version: 'v2'
      layer2_kwargs:
        gat_version: 'v2'
