_internal_variables:
  template: !update 'config/node_classification/template.yaml'
  model_name: &model_name 'GAT2'

logs:
  name: !join [*model_name, v2_base]

module:
  model:
    name: *model_name
    kwargs:
      hidden_feat: 128
      layer1_kwargs:
        gat_version: 'v2'
      layer2_kwargs:
        gat_version: 'v2'
