_internal_variables:
  template: !update 'config/node_classification/template.yaml'
  model_name: &model_name 'GCNII'

logs:
  name: !join [*model_name, _base]

module:
  optimizer:
    lr: 1e-3

  model:
    name: *model_name
    kwargs:
      hidden_feat: 128
      in_features: None
      num_layers: 8
      alpha: 0.1
      theta: 0.5
