_internal_variables:
  - &home_path !home_path

mode: NodesClassification
cross_validation:
  split: 5

logs:
  save_dir: !join [*home_path, /results/plant-ct-logs/baseline/]

trainer:
  gpus: 1
  max_epochs: 10

loader:
  path: !join [*home_path, /data/ovules/ovules-celltype-processed/]
  load_edge_attr: false
  batch: 1

module:
  logger:
    log_points: false

  optimizer:
    lr: 1e-4
    wd: 1e-5

  model:
    kwargs:
      out_features: 9