
logs:
  path: "/results/plant-ct-logs/baseline/"
  run_keyword: "base"

trainer:
  gpus: 1
  max_steps: 12000

loader:
  path: "/data/ovules/ovules-celltype-processed/**/*.h5"
  load_edge_attr: false
  batch: 1

pl_lightning:
  config_optimizer:
    lr: 1e-4
    wd: 1e-6

  config_model:
    name: 'TransformerGCN2'
    kwargs:
      out_features: 10
      hidden_feat: 128
