_internal_variables:
  - &home_path !home_path

preprocessing:
  state: false
  train_data_voxels_size: [0.25, 0.2, 0.2]
  default_seg_key: 'segmentation'
  file_list: !join [*home_path, '/Downloads/tejasvinee/predictions_segmentations/1135_segmentation.tiff']
  out_dir: &out_dir !join [*home_path, '/Downloads/test_ct/']

grs_step:
  state: false
  mode: trivial_grs
  file_list: !join [*out_dir, '*']

advanced_features_step:
  state: false
  file_list: !join [*out_dir, '*']

ct_predictions:
  state: true
  mode: 'NodesClassification'

  loader:
    files_list: !join [*out_dir, '*']
    load_edge_attr: true

  checkpoint: !join [*home_path, '/hci/results/plant-ct-logs/best_deepGCN/trivial_grs/version_0/']
