_internal_variables:
  template: !update 'example_config/node_classification/template.yaml'
  model_name: &model_name 'TgGCN'

logs:
  name: *model_name

module:
  optimizer:
    lr: 1e-3
    wd: 0

  model:
    name: *model_name
    kwargs:
      hidden_feat: 128
      dropout: 0.5
      num_layers: 4
      out_features: 9
