_internal_variables:
  - &home_path !home_path
  - &root !join [*home_path, '/data/ctg_features/']
  - &force_process false
  - &num_workers 4

mode: NodesClassification
seed: 0

logs:
  save_dir: !join [*home_path, '/results/plant-ct-logs/baseline/']

trainer:
  gpus: 1
  # max_steps: 15000
  max_epochs: 100

loader:
  mode: simple # simple or cross_validation
  train_dataset:
    root: *root
    phase: train
    ratio: [0.6, 0.1, 0.3]
    grs: [label_grs_surface]
    force_process: *force_process

  val_dataset:
    root: *root
    phase: val
    ratio: [0.6, 0.1, 0.3]
    grs: [label_grs_surface]
    force_process: *force_process

  test_dataset:
    root: *root
    phase: test
    ratio: [ 0.6, 0.1, 0.3 ]
    grs: [ label_grs_surface ]
    force_process: *force_process

  num_workers: *num_workers
  train_batch_size: 1
  val_batch_size: 1

module:
  logger:
    log_points: false

  optimizer:
    lr: 1e-3
    wd: 0

  model:
    kwargs:
      out_features: 9