_internal_variables:
  template: !update 'config/features/gcn/template.yaml'
  model_name: &model_name 'GCN2'

logs:
  name: !join [*model_name, _base]

module:
  model:
    name: *model_name
    kwargs:
      hidden_feat: 128
      layer1_kwargs:
        batch_norm: false
        drop_out: 0.5
