package:
  name: plantcelltype
  version: {{ RELEASE_VERSION }}

source:
  path: ..

build:
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

  entry_points:
    - plantcelltype = plantcelltype.run_dataprocessing:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - ctg-benchmark
    - tifffile
    - scikit-image
    - scikit-spatial
    - python-elf
    - pytorch-lightning

about:
  home: https://github.com/hci-unihd/plant-celltype
  license: MIT