package:
  name: plantct
  version: {{ RELEASE_VERSION }}

source:
  path: ..

build:
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

  entry_points:
    - plantct = plantseg.run_pipeline:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - tqdm
    - h5py
    - requests
    - pyyaml
    - scikit-image
    - tifffile
    - scikit-spatial
    - scikit-imagew
    - python-elf
    - pytorch
    - pytorch-metrics
    - pytorch-lightning
    - pytorch-geometric


about:
  home: https://github.com/hci-unihd/plant-celltype
  license: MIT