_internal_variables:
  - &home_path !home_path
  - &model_name 'DeeperGCN'

mode: NodesClassification

logs:
  save_dir: !join [*home_path, /results/plant-ct-logs/baseline/]

loader:
  path: !join [*home_path, /data/ovules/ovules-celltype-new/label_grs_surface/late_cropped_ds3/]
  load_edge_attr: true
  batch: 1
  test_batch: 1

module:
  logger:
    log_points: false

  optimizer:
    lr: 1e-2
    wd: 0

  model:
    name: *model_name
    kwargs:
      hidden_feat: 128
      in_features: None
      out_features: 9
      num_layers: 16
      dropout: 0.1

trainer:
  gpus: 1
  max_epochs: 50