_internal_variables:
  - &home_path !home_path
  - &model_name 'GCN2'

mode: NodesClassification

logs:
  save_dir: !join [*home_path, /results/plant-ct-logs/best_GCN2/]

loader:
  load_edge_attr: false
  batch: 1
  test_batch: 1

module:
  logger:
    log_points: false

  optimizer:
    lr: 1e-3
    wd: 0

  model:
    name: *model_name
    kwargs:
      hidden_feat: 128
      in_features: None
      out_features: 9
      layer1_kwargs:
        batch_norm: false
        drop_out: 0.5

trainer:
  gpus: 1
  max_epochs: 50