_internal_variables:
  template: !update 'config/test_grs/template.yaml'
  model_name: &grs 'trivial_grs'
  home_path: &home_path !home_path

logs:
  name: *grs

loader:
  path: !join [*home_path, /data/ovules/ovules-celltype-new/, *grs, /late_cropped_ds3/]