_internal_variables:
  template: !update 'config/node_classification_grid_search/template.yaml'
  model_name: &model_name 'DeeperGCN'

logs:
  name: *model_name

loader:
  load_edge_attr: true

module:
  model:
    name: *model_name
    kwargs:
      hidden_feat: 64
      in_features: None
      num_layers: 28

grid_search:
  module/optimizer/lr: [ 1e-2, 1e-3, 1e-4 ]
  module/optimizer/wd: [ 0, 1e-5 ]
  module/model/kwargs/hidden_feat: [ 16, 32, 64, 128 ]
  module/model/kwargs/num_layers: [ 2, 4, 8, 16, 32, 64]
  module/model/kwargs/dropout: [ 0., 0.1, 0.5 ]
  loader/batch: [ 1, 5 ]