_internal_variables:
  template: !update 'config/node_classification_grid_search/template.yaml'
  model_name: &model_name 'GCNII'

logs:
  name: !join [*model_name, _base]

module:
  optimizer:
    lr: 1e-3

  model:
    name: *model_name
    kwargs:
      hidden_feat: 128
      in_features: None
      num_layers: 8
      alpha: 0.1
      theta: 0.5

grid_search:
  module/optimizer/lr: [ 1e-2, 1e-3, 1e-4 ]
  module/optimizer/wd: [ 0, 1e-5 ]
  module/model/kwargs/hidden_feat: [ 16, 32, 64, 128 ]
  module/model/kwargs/num_layers: [ 2, 4, 8, 16, 32]
  module/model/kwargs/dropout: [ 0., 0.5 ]
  module/model/kwargs/shared_weights: [ true, false ]
  loader/batch: [ 1, 5 ]