_internal_variables:
  - &home_path !home_path

mode: NodesClassification

logs:
  save_dir: !join [*home_path, /results/plant-ct-logs/grid_search/]

trainer:
  gpus: 1
  # max_steps: 15000
  max_epochs: 200

loader:
  path: !join [*home_path, /data/ovules/ovules-celltype-processed/]
  load_edge_attr: false
  batch: 1
  test_batch: 1

module:
  logger:
    log_points: false

  optimizer:
    lr: 1e-4
    wd: 1e-5

  model:
    kwargs:
      out_features: 9